services:
  - type: web
    name: orderflow-pro
    env: node
    rootDir: .
    plan: starter
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: TZ
        value: Europe/Paris
      - key: DB_PATH
        value: /var/data/orderflow.sqlite
      - key: NIXPACKS_NODE_VERSION          # <= ceinture + bretelles pour Node 18
        value: "18"
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
